name: Calendar Test Run

on:
  workflow_dispatch: # 手動で「Run workflow」ボタンから実行
  # schedule:
  #   - cron: '0 18 * * *' # 毎日18時(UTC) = 3時（JST）に自動実行 ⚠️ テスト終わったらコメントアウトを解除

jobs:
  build:
    runs-on: ubuntu-latest
    
    # リポジトリにファイルを書き込む権限を付与
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4 # GitHub のリポジトリのコードをワークフロー環境にダウンロード（コピー）

      - name: Setup Node.js # Node.jsをインストールするためのアクション
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies # 外部ライブラリを package.json のリストに基づいてダウンロード
        run: npm install

      - name: Run script
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          TARGET_ACCOUNT: ${{ secrets.TARGET_ACCOUNT }}
          TZ: 'Asia/Tokyo' # 日本時間で実行
        run: npx tsx index.ts

      # 新しくできたファイルを GitHub に保存する
      - name: Commit and Push changes
        if: ${{ env.ACT != 'true' }}
        run: |
          git config --global core.quotepath false
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # meetings,inbox フォルダの中身をすべてステージング
          git add meetings/ inbox/
          
          # 変更がある場合のみ保存（コミット）してアップロード（プッシュ）
          if ! git diff --cached --exit-code; then
            git commit -m "Add meeting summaries by AI [skip ci]"
            git push
          else
            echo "保存する変更はありませんでした。"
          fi